language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly-2019-04-14

install:
  - rustup component add rustfmt clippy

script:
  - cargo build --all-features --verbose
  - cargo test --all-features --verbose
  - cargo clippy
  - cargo clippy -- -Dwarnings
  - cargo clippy --tests -- -Dwarnings
  - cargo fmt --all -- --check

deploy:
  provider: script
  on:
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable
  script: >-
    cargo install -f cargo-tarpaulin &&
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
