language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly-2019-04-14

install:
  - rustup component add rustfmt clippy
  - if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then cargo install -f cargo-tarpaulin; fi

script:
  - cargo build --all-features --verbose
  - cargo test --all-features --verbose
  - cargo clippy
  - cargo clippy -- -Dwarnings
  - cargo clippy --tests -- -Dwarnings
  - cargo fmt --all -- --check

after_success:
  - if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID; fi
